[project]
name = "chirpstack-docker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chirpstack-api>=4.13.0",
    "paho-mqtt>=2.1.0",
    "rich>=14.1.0",
    "requests>=2.31.0",
    "typer>=0.16.0",
]
